create table "BIOMETRIC".USERS
(
	INDEX_NUMBER CHAR(7) not null primary key,
	USER_NAME VARCHAR(40) default 'NULL',
	MIDDLE_FINGER FLOAT default NULL,
	INDEX_FINGER FLOAT default NULL,
	PINKY_FINGER FLOAT default NULL,
	RING_FINGER FLOAT default NULL,
	THUMB FLOAT default NULL,
	PALM_WIDTH FLOAT default NULL,
	PALM_HEIGHT FLOAT default NULL,
	INDEX_WIDTH FLOAT,
	MIDDLE_WIDTH FLOAT,
	RING_WIDTH FLOAT,
	PINKY_WIDTH FLOAT,
	THUMB_WIDTH FLOAT
)
