package lk.bhanuka.biometric.models;
// Generated Mar 1, 2017 4:11:21 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String indexNumber;
     private String name;
     private Float middleFinger;
     private Float indexFinger;
     private Float pinkyFinger;
     private Float ringFinger;
     private Float thumb;
     private Float palmWidth;
     private Float palmHeight;

    public User() {
    }

	
    public User(String indexNumber) {
        this.indexNumber = indexNumber;
    }
    public User(String indexNumber, String name, Float middleFinger, Float indexFinger, Float pinkyFinger, Float ringFinger, Float palmWidth, Float palmHeight) {
       this.indexNumber = indexNumber;
       this.name = name;
       this.middleFinger = middleFinger;
       this.indexFinger = indexFinger;
       this.pinkyFinger = pinkyFinger;
       this.ringFinger = ringFinger;
       this.palmWidth = palmWidth;
       this.palmHeight = palmHeight;
       this.thumb = 0.0f;
    }
    
    public User(String indexNumber, String name, Float middleFinger, Float indexFinger, Float pinkyFinger, Float ringFinger,Float thumb, Float palmWidth, Float palmHeight) {
       this.indexNumber = indexNumber;
       this.name = name;
       this.middleFinger = middleFinger;
       this.indexFinger = indexFinger;
       this.pinkyFinger = pinkyFinger;
       this.ringFinger = ringFinger;
       this.palmWidth = palmWidth;
       this.palmHeight = palmHeight;
       this.thumb = thumb;
    }
   
    public String getIndexNumber() {
        return this.indexNumber;
    }
    
    public void setIndexNumber(String indexNumber) {
        this.indexNumber = indexNumber;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getMiddleFinger() {
        return this.middleFinger;
    }
    
    public void setMiddleFinger(Float middleFinger) {
        this.middleFinger = middleFinger;
    }
    public Float getIndexFinger() {
        return this.indexFinger;
    }
    
    public void setIndexFinger(Float indexFinger) {
        this.indexFinger = indexFinger;
    }
    public Float getPinkyFinger() {
        return this.pinkyFinger;
    }
    
    public void setPinkyFinger(Float pinkyFinger) {
        this.pinkyFinger = pinkyFinger;
    }
    public Float getRingFinger() {
        return this.ringFinger;
    }
    
    public void setThumb(Float thumb){
        this.thumb = thumb;
    }
    public Float getThumb(){
        return this.thumb;
    }
    
    public void setRingFinger(Float ringFinger) {
        this.ringFinger = ringFinger;
    }
    public Float getPalmWidth() {
        return this.palmWidth;
    }
    
    public void setPalmWidth(Float palmWidth) {
        this.palmWidth = palmWidth;
    }
    public Float getPalmHeight() {
        return this.palmHeight;
    }
    
    public void setPalmHeight(Float palmHeight) {
        this.palmHeight = palmHeight;
    }




}


